// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5fjDn240BvyeP8ocFENd-qNFus1vvHdM',
    appId: '1:1050107042949:web:b10fd5b384192c223c5dec',
    messagingSenderId: '1050107042949',
    projectId: 'suefery-d2bf2',
    authDomain: 'suefery-d2bf2.firebaseapp.com',
    storageBucket: 'suefery-d2bf2.firebasestorage.app',
    measurementId: 'G-H0RRE4D940',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ_s8ptPgU8hPx9xdkuPkLpsXodDHT1gQ',
    appId: '1:1050107042949:android:903b4a22897dfb193c5dec',
    messagingSenderId: '1050107042949',
    projectId: 'suefery-d2bf2',
    storageBucket: 'suefery-d2bf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTCSEHY49KnW6BQP7Yd1tAGCaJbK0OTIo',
    appId: '1:1050107042949:ios:81058aa49278d5cc3c5dec',
    messagingSenderId: '1050107042949',
    projectId: 'suefery-d2bf2',
    storageBucket: 'suefery-d2bf2.firebasestorage.app',
    iosClientId: '1050107042949-ougrbq42mvqh7lk8d6l5nn5ukai956oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.suefery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTCSEHY49KnW6BQP7Yd1tAGCaJbK0OTIo',
    appId: '1:1050107042949:ios:81058aa49278d5cc3c5dec',
    messagingSenderId: '1050107042949',
    projectId: 'suefery-d2bf2',
    storageBucket: 'suefery-d2bf2.firebasestorage.app',
    iosClientId: '1050107042949-ougrbq42mvqh7lk8d6l5nn5ukai956oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.suefery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5fjDn240BvyeP8ocFENd-qNFus1vvHdM',
    appId: '1:1050107042949:web:32e6a6574c0a88753c5dec',
    messagingSenderId: '1050107042949',
    projectId: 'suefery-d2bf2',
    authDomain: 'suefery-d2bf2.firebaseapp.com',
    storageBucket: 'suefery-d2bf2.firebasestorage.app',
    measurementId: 'G-VLRHMSKLZJ',
  );

}